import { AwsServiceType, CanvasEdge, CanvasNode } from '@infra-builder/state';

type Props = Record<string, unknown>;

export interface CfResource {
  Type: string;
  Properties?: Props;
  DependsOn?: string[];
}

export interface CfTemplate {
  AWSTemplateFormatVersion: string;
  Description: string;
  Parameters?: Record<string, Props>;
  Resources: Record<string, CfResource>;
}

const RESOURCE_TYPES: Record<AwsServiceType, string> = {
  vpc: 'AWS::EC2::VPC',
  subnet: 'AWS::EC2::Subnet',
  'internet-gateway': 'AWS::EC2::InternetGateway',
  'nat-gateway': 'AWS::EC2::NatGateway',
  ec2: 'AWS::EC2::Instance',
  lambda: 'AWS::Lambda::Function',
  ecs: 'AWS::ECS::Cluster',
  s3: 'AWS::S3::Bucket',
  ebs: 'AWS::EC2::Volume',
  rds: 'AWS::RDS::DBInstance',
  dynamodb: 'AWS::DynamoDB::Table',
  'iam-role': 'AWS::IAM::Role',
  'security-group': 'AWS::EC2::SecurityGroup',
  alb: 'AWS::ElasticLoadBalancingV2::LoadBalancer',
  sqs: 'AWS::SQS::Queue',
  sns: 'AWS::SNS::Topic',
  eventbridge: 'AWS::Events::EventBus',
  'api-gateway': 'AWS::ApiGatewayV2::Api',
  kinesis: 'AWS::Kinesis::Stream',
};

const LATEST_AL2023 =
  '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64}}';

const NODE_STUB = 'exports.handler = async () => ({ statusCode: 200 });';
const PYTHON_STUB =
  'def handler(event, context):\n    return {"statusCode": 200}';

const DEFAULT_PROPS: Partial<Record<AwsServiceType, Props>> = {
  vpc: {
    CidrBlock: '10.0.0.0/16',
    EnableDnsSupport: true,
    EnableDnsHostnames: true,
  },
  ec2: { InstanceType: 't3.micro', ImageId: LATEST_AL2023 },
  lambda: { Runtime: 'nodejs22.x', Handler: 'index.handler' },
  s3: {
    BucketEncryption: {
      ServerSideEncryptionConfiguration: [
        { ServerSideEncryptionByDefault: { SSEAlgorithm: 'AES256' } },
      ],
    },
  },
  ebs: {
    Size: 8,
    AvailabilityZone: { 'Fn::Select': [0, { 'Fn::GetAZs': '' }] },
  },
  rds: {
    DBInstanceClass: 'db.t3.micro',
    Engine: 'mysql',
    AllocatedStorage: 20,
    MasterUsername: { Ref: 'DBUsername' },
    MasterUserPassword: { Ref: 'DBPassword' },
  },
  dynamodb: {
    KeySchema: [{ AttributeName: 'id', KeyType: 'HASH' }],
    AttributeDefinitions: [{ AttributeName: 'id', AttributeType: 'S' }],
    BillingMode: 'PAY_PER_REQUEST',
  },
  'iam-role': {
    AssumeRolePolicyDocument: assumeRole(
      'lambda.amazonaws.com',
      'ec2.amazonaws.com',
    ),
  },
  'security-group': { GroupDescription: 'Security group' },
  alb: { Type: 'application', Scheme: 'internet-facing' },
  'api-gateway': { ProtocolType: 'HTTP' },
  kinesis: { ShardCount: 1 },
};

const POLICY = {
  basic: 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole',
  vpc: 'arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole',
  sqs: 'arn:aws:iam::aws:policy/service-role/AWSLambdaSQSQueueExecutionRole',
  kinesis: 'arn:aws:iam::aws:policy/service-role/AWSLambdaKinesisExecutionRole',
  dynamodb:
    'arn:aws:iam::aws:policy/service-role/AWSLambdaDynamoDBExecutionRole',
};

/** Per-service AWS principal that may invoke a Lambda. */
const INVOKE_PRINCIPALS: Partial<Record<AwsServiceType, string>> = {
  s3: 's3.amazonaws.com',
  sns: 'sns.amazonaws.com',
  eventbridge: 'events.amazonaws.com',
  'api-gateway': 'apigateway.amazonaws.com',
  alb: 'elasticloadbalancing.amazonaws.com',
};

const STREAM_SOURCES: Partial<
  Record<AwsServiceType, { props: Props; policy: string }>
> = {
  sqs: { props: { BatchSize: 10 }, policy: POLICY.sqs },
  kinesis: {
    props: { BatchSize: 100, StartingPosition: 'LATEST' },
    policy: POLICY.kinesis,
  },
  dynamodb: {
    props: { BatchSize: 100, StartingPosition: 'LATEST' },
    policy: POLICY.dynamodb,
  },
};

export function buildTemplate(
  nodes: CanvasNode[],
  edges: CanvasEdge[],
): CfTemplate {
  const ctx = new Builder(nodes);
  nodes.forEach((n) => ctx.addResource(n));
  nodes.forEach((n) => ctx.applyContainment(n));
  edges.forEach((e) => ctx.applyEdge(e));
  ctx.finish();

  const template: CfTemplate = {
    AWSTemplateFormatVersion: '2010-09-09',
    Description: 'Generated by InfraBuilder',
    Resources: ctx.resources,
  };
  if (Object.keys(ctx.parameters).length) template.Parameters = ctx.parameters;
  return template;
}

class Builder {
  readonly resources: Record<string, CfResource> = {};
  readonly parameters: Record<string, Props> = {};
  private readonly ids = new Map<string, string>();
  private readonly byId: Map<string, CanvasNode>;
  /** Managed policies each Lambda's role must carry, keyed by Lambda node id. */
  private readonly lambdaPolicies = new Map<string, Set<string>>();
  /** Logical id of the user-drawn role attached to a Lambda, if any. */
  private readonly lambdaRoles = new Map<string, string>();
  private readonly gatewayAttachments = new Map<string, string>();
  private readonly volumeCount = new Map<string, number>();

  constructor(private nodes: CanvasNode[]) {
    this.byId = new Map(nodes.map((n) => [n.id, n]));
    const used = new Set<string>();
    nodes.forEach((n) => {
      const base = toPascal(n.label) || toPascal(n.type) || 'Resource';
      let id = base;
      for (let i = 2; used.has(id); i++) id = `${base}${i}`;
      used.add(id);
      this.ids.set(n.id, id);
    });
  }

  id(nodeId: string): string {
    return this.ids.get(nodeId) as string;
  }

  props(nodeId: string): Props {
    const resource = this.resources[this.id(nodeId)];
    return (resource.Properties ??= {});
  }

  addResource(node: CanvasNode): void {
    const userProps = Object.fromEntries(
      Object.entries(node.properties).map(([k, v]) => [k, coerce(v)]),
    );
    const props: Props = { ...DEFAULT_PROPS[node.type], ...userProps };
    this.resources[this.id(node.id)] = {
      Type: RESOURCE_TYPES[node.type],
      Properties: props,
    };

    switch (node.type) {
      case 'rds':
        this.parameters['DBUsername'] = { Type: 'String', Default: 'dbadmin' };
        this.parameters['DBPassword'] = { Type: 'String', NoEcho: true };
        break;
      case 'lambda':
        props['Code'] ??= {
          ZipFile: String(props['Runtime']).startsWith('python')
            ? PYTHON_STUB
            : NODE_STUB,
        };
        break;
      case 'dynamodb':
        if (props['BillingMode'] === 'PROVISIONED') {
          props['ProvisionedThroughput'] ??= {
            ReadCapacityUnits: 5,
            WriteCapacityUnits: 5,
          };
        }
        break;
      case 'api-gateway':
        props['Name'] ??= node.label;
        break;
      case 'subnet': {
        // Spread sibling subnets over AZs and non-overlapping CIDRs.
        const vpc = this.ancestor(node, 'vpc');
        const index = this.subnetsIn(vpc).indexOf(node);
        props['CidrBlock'] ??= `10.0.${index + 1}.0/24`;
        props['AvailabilityZone'] ??= {
          'Fn::Select': [index % 2, { 'Fn::GetAZs': '' }],
        };
        break;
      }
    }
  }

  applyContainment(node: CanvasNode): void {
    const vpc = this.ancestor(node, 'vpc');
    const subnet = this.ancestor(node, 'subnet');
    const props = this.props(node.id);
    const vpcSubnets = this.subnetsIn(vpc).map((s) => ref(this.id(s.id)));

    switch (node.type) {
      case 'subnet':
      case 'security-group':
        if (vpc) props['VpcId'] = ref(this.id(vpc.id));
        break;
      case 'ec2':
        if (subnet) props['SubnetId'] = ref(this.id(subnet.id));
        break;
      case 'nat-gateway':
        if (subnet) {
          const eip = `${this.id(node.id)}Eip`;
          this.resources[eip] = {
            Type: 'AWS::EC2::EIP',
            Properties: { Domain: 'vpc' },
          };
          props['SubnetId'] = ref(this.id(subnet.id));
          props['AllocationId'] = getAtt(eip, 'AllocationId');
        }
        break;
      case 'lambda':
        if (subnet) {
          this.vpcConfig(node.id, 'SubnetIds', ref(this.id(subnet.id)));
          this.policy(node.id, POLICY.vpc);
        }
        break;
      case 'alb':
        // ALBs need two subnets in different AZs; use every subnet in the VPC.
        if (subnet) props['Subnets'] = vpcSubnets;
        break;
      case 'rds':
        if (subnet) {
          const group = `${this.id(node.id)}SubnetGroup`;
          this.resources[group] = {
            Type: 'AWS::RDS::DBSubnetGroup',
            Properties: {
              DBSubnetGroupDescription: `Subnets for ${node.label}`,
              SubnetIds: vpcSubnets,
            },
          };
          props['DBSubnetGroupName'] = ref(group);
        }
        break;
    }
  }

  applyEdge(edge: CanvasEdge): void {
    const source = this.byId.get(edge.sourceNodeId);
    const target = this.byId.get(edge.targetNodeId);
    if (!source || !target) return;
    const edgeProps = Object.fromEntries(
      Object.entries(edge.properties ?? {}).map(([k, v]) => [k, coerce(v)]),
    );

    switch (edge.kind) {
      case 'trigger':
        this.applyTrigger(source, target, edgeProps);
        break;
      case 'attaches':
        this.applyAttachment(source, target);
        break;
      case 'network':
        this.applyNetwork(source, target);
        break;
      default:
        this.dependsOn(target.id, this.id(source.id));
    }
  }

  private applyTrigger(source: CanvasNode, target: CanvasNode, p: Props): void {
    const sourceId = this.id(source.id);
    const targetId = this.id(target.id);
    const targetArn = getAtt(targetId, 'Arn');

    if (target.type === 'lambda') {
      const principal = INVOKE_PRINCIPALS[source.type];
      if (principal) {
        this.resources[`${targetId}${sourceId}Permission`] = {
          Type: 'AWS::Lambda::Permission',
          Properties: {
            Action: 'lambda:InvokeFunction',
            FunctionName: ref(targetId),
            Principal: principal,
            SourceAccount: ref('AWS::AccountId'),
          },
        };
      }
      const stream = STREAM_SOURCES[source.type];
      if (stream) {
        const arnAttr = source.type === 'dynamodb' ? 'StreamArn' : 'Arn';
        if (source.type === 'dynamodb') {
          this.props(source.id)['StreamSpecification'] = {
            StreamViewType: 'NEW_AND_OLD_IMAGES',
          };
        }
        this.resources[`${targetId}${sourceId}Mapping`] = {
          Type: 'AWS::Lambda::EventSourceMapping',
          Properties: {
            ...stream.props,
            ...p,
            EventSourceArn: getAtt(sourceId, arnAttr),
            FunctionName: ref(targetId),
          },
        };
        this.policy(target.id, stream.policy);
        return;
      }
    }

    switch (source.type) {
      case 's3':
        this.applyS3Notification(source, target, p);
        break;
      case 'sns':
        this.resources[`${sourceId}${targetId}Subscription`] = {
          Type: 'AWS::SNS::Subscription',
          Properties: {
            TopicArn: ref(sourceId),
            Protocol: target.type === 'sqs' ? 'sqs' : 'lambda',
            Endpoint: targetArn,
          },
        };
        if (target.type === 'sqs') {
          this.allowQueueSender(target, 'sns.amazonaws.com', ref(sourceId));
        }
        break;
      case 'eventbridge': {
        const rule: Props = {
          Targets: [{ Arn: targetArn, Id: targetId }],
        };
        if (p['ScheduleExpression']) {
          rule['ScheduleExpression'] = p['ScheduleExpression'];
        } else {
          rule['EventBusName'] = ref(sourceId);
          rule['EventPattern'] = {
            source: [{ 'Fn::Sub': '${AWS::StackName}' }],
          };
        }
        this.resources[`${sourceId}${targetId}Rule`] = {
          Type: 'AWS::Events::Rule',
          Properties: rule,
        };
        if (target.type === 'sqs') {
          this.allowQueueSender(
            target,
            'events.amazonaws.com',
            getAtt(`${sourceId}${targetId}Rule`, 'Arn'),
          );
        }
        break;
      }
      case 'api-gateway': {
        const integration = `${sourceId}${targetId}Integration`;
        this.resources[integration] = {
          Type: 'AWS::ApiGatewayV2::Integration',
          Properties: {
            ApiId: ref(sourceId),
            IntegrationType: 'AWS_PROXY',
            IntegrationUri: targetArn,
            PayloadFormatVersion: '2.0',
          },
        };
        this.resources[`${sourceId}${targetId}Route`] = {
          Type: 'AWS::ApiGatewayV2::Route',
          Properties: {
            ApiId: ref(sourceId),
            RouteKey: p['RouteKey'] ?? '$default',
            Target: { 'Fn::Sub': `integrations/\${${integration}}` },
          },
        };
        this.resources[`${sourceId}Stage`] ??= {
          Type: 'AWS::ApiGatewayV2::Stage',
          Properties: {
            ApiId: ref(sourceId),
            StageName: '$default',
            AutoDeploy: true,
          },
        };
        break;
      }
    }
  }

  private applyS3Notification(
    bucket: CanvasNode,
    target: CanvasNode,
    p: Props,
  ): void {
    const bucketId = this.id(bucket.id);
    const targetId = this.id(target.id);
    const config: Props = { Event: p['Event'] ?? 's3:ObjectCreated:*' };
    if (p['Prefix']) {
      config['Filter'] = {
        S3Key: { Rules: [{ Name: 'prefix', Value: p['Prefix'] }] },
      };
    }
    const notification = this.notification(bucket.id);
    switch (target.type) {
      case 'lambda':
        push(notification, 'LambdaConfigurations', {
          ...config,
          Function: getAtt(targetId, 'Arn'),
        });
        this.dependsOn(bucket.id, `${targetId}${bucketId}Permission`);
        break;
      case 'sqs':
        push(notification, 'QueueConfigurations', {
          ...config,
          Queue: getAtt(targetId, 'Arn'),
        });
        this.allowQueueSender(target, 's3.amazonaws.com');
        this.dependsOn(bucket.id, `${targetId}Policy`);
        break;
      case 'sns':
        push(notification, 'TopicConfigurations', {
          ...config,
          Topic: ref(targetId),
        });
        this.resources[`${targetId}Policy`] ??= {
          Type: 'AWS::SNS::TopicPolicy',
          Properties: {
            Topics: [ref(targetId)],
            PolicyDocument: {
              Version: '2012-10-17',
              Statement: [
                {
                  Effect: 'Allow',
                  Principal: { Service: 's3.amazonaws.com' },
                  Action: 'sns:Publish',
                  Resource: ref(targetId),
                  Condition: {
                    StringEquals: {
                      'aws:SourceAccount': ref('AWS::AccountId'),
                    },
                  },
                },
              ],
            },
          },
        };
        this.dependsOn(bucket.id, `${targetId}Policy`);
        break;
    }
  }

  /** Grants a service principal permission to send to an SQS queue. */
  private allowQueueSender(
    queue: CanvasNode,
    service: string,
    sourceArn?: Props,
  ): void {
    const queueId = this.id(queue.id);
    const policyId = `${queueId}Policy`;
    this.resources[policyId] ??= {
      Type: 'AWS::SQS::QueuePolicy',
      Properties: {
        Queues: [ref(queueId)],
        PolicyDocument: { Version: '2012-10-17', Statement: [] },
      },
    };
    const doc = (this.resources[policyId].Properties as Props)[
      'PolicyDocument'
    ] as Props;
    push(doc, 'Statement', {
      Effect: 'Allow',
      Principal: { Service: service },
      Action: 'sqs:SendMessage',
      Resource: getAtt(queueId, 'Arn'),
      Condition: sourceArn
        ? { ArnEquals: { 'aws:SourceArn': sourceArn } }
        : { StringEquals: { 'aws:SourceAccount': ref('AWS::AccountId') } },
    });
  }

  private applyAttachment(source: CanvasNode, target: CanvasNode): void {
    const sourceId = this.id(source.id);
    const targetId = this.id(target.id);
    const targetProps = this.props(target.id);

    if (source.type === 'iam-role') {
      if (target.type === 'lambda') {
        targetProps['Role'] = getAtt(sourceId, 'Arn');
        this.lambdaRoles.set(target.id, sourceId);
        this.policy(target.id, POLICY.basic);
      } else if (target.type === 'ec2') {
        const profile = `${sourceId}InstanceProfile`;
        this.resources[profile] ??= {
          Type: 'AWS::IAM::InstanceProfile',
          Properties: { Roles: [ref(sourceId)] },
        };
        targetProps['IamInstanceProfile'] = ref(profile);
      }
    } else if (source.type === 'security-group') {
      const key: Partial<Record<AwsServiceType, string>> = {
        ec2: 'SecurityGroupIds',
        rds: 'VPCSecurityGroups',
        alb: 'SecurityGroups',
      };
      if (target.type === 'lambda') {
        this.vpcConfig(target.id, 'SecurityGroupIds', ref(sourceId));
      } else if (key[target.type]) {
        push(targetProps, key[target.type] as string, ref(sourceId));
      }
    } else if (source.type === 'ebs' && target.type === 'ec2') {
      const index = this.volumeCount.get(target.id) ?? 0;
      this.volumeCount.set(target.id, index + 1);
      this.props(source.id)['AvailabilityZone'] = getAtt(
        targetId,
        'AvailabilityZone',
      );
      this.resources[`${targetId}${sourceId}Attachment`] = {
        Type: 'AWS::EC2::VolumeAttachment',
        Properties: {
          InstanceId: ref(targetId),
          VolumeId: ref(sourceId),
          Device: `/dev/sd${String.fromCharCode(102 + index)}`,
        },
      };
    }
  }

  private applyNetwork(source: CanvasNode, target: CanvasNode): void {
    const sourceId = this.id(source.id);
    const targetId = this.id(target.id);

    if (source.type === 'internet-gateway' && target.type === 'vpc') {
      const attachment = `${targetId}${sourceId}Attachment`;
      this.resources[attachment] = {
        Type: 'AWS::EC2::VPCGatewayAttachment',
        Properties: { VpcId: ref(targetId), InternetGatewayId: ref(sourceId) },
      };
      this.gatewayAttachments.set(target.id, attachment);
    } else if (source.type === 'alb') {
      const vpc = this.ancestor(source, 'vpc');
      const group = `${sourceId}TargetGroup`;
      this.resources[group] ??= {
        Type: 'AWS::ElasticLoadBalancingV2::TargetGroup',
        Properties: {
          TargetType: target.type === 'lambda' ? 'lambda' : 'instance',
          ...(target.type === 'lambda'
            ? {}
            : {
                Port: 80,
                Protocol: 'HTTP',
                VpcId: vpc && ref(this.id(vpc.id)),
              }),
          Targets: [],
        },
      };
      const groupProps = this.resources[group].Properties as Props;
      if (target.type === 'lambda') {
        push(groupProps, 'Targets', { Id: getAtt(targetId, 'Arn') });
        const permission = `${targetId}${sourceId}Permission`;
        this.resources[permission] = {
          Type: 'AWS::Lambda::Permission',
          Properties: {
            Action: 'lambda:InvokeFunction',
            FunctionName: ref(targetId),
            Principal: INVOKE_PRINCIPALS.alb,
          },
        };
        this.resources[group].DependsOn = [permission];
      } else {
        push(groupProps, 'Targets', { Id: ref(targetId) });
      }
      this.resources[`${sourceId}Listener`] ??= {
        Type: 'AWS::ElasticLoadBalancingV2::Listener',
        Properties: {
          LoadBalancerArn: ref(sourceId),
          Port: 80,
          Protocol: 'HTTP',
          DefaultActions: [{ Type: 'forward', TargetGroupArn: ref(group) }],
        },
      };
    } else {
      this.dependsOn(target.id, sourceId);
    }
  }

  finish(): void {
    this.nodes.forEach((node) => {
      if (node.type === 'lambda') this.finishLambda(node);
      if (node.type === 'nat-gateway') {
        const vpc = this.ancestor(node, 'vpc');
        const attachment = vpc && this.gatewayAttachments.get(vpc.id);
        if (attachment) this.dependsOn(node.id, attachment);
      }
    });
  }

  private finishLambda(node: CanvasNode): void {
    const props = this.props(node.id);
    const config = props['VpcConfig'] as Props | undefined;
    if (config && !config['SecurityGroupIds']) {
      // Lambda requires SubnetIds and SecurityGroupIds together.
      const vpc = this.ancestor(node, 'vpc');
      const sg = `${this.id(node.id)}SecurityGroup`;
      this.resources[sg] = {
        Type: 'AWS::EC2::SecurityGroup',
        Properties: {
          GroupDescription: `Access for ${node.label}`,
          ...(vpc ? { VpcId: ref(this.id(vpc.id)) } : {}),
        },
      };
      config['SecurityGroupIds'] = [ref(sg)];
    }

    const policies = this.lambdaPolicies.get(node.id) ?? new Set<string>();
    const roleId = this.lambdaRoles.get(node.id);
    if (roleId) {
      const role = this.resources[roleId].Properties as Props;
      const arns = new Set([
        ...((role['ManagedPolicyArns'] as string[] | undefined) ?? []),
        ...policies,
      ]);
      role['ManagedPolicyArns'] = [...arns];
      return;
    }

    const shared = 'LambdaExecutionRole';
    this.resources[shared] ??= {
      Type: 'AWS::IAM::Role',
      Properties: {
        AssumeRolePolicyDocument: assumeRole('lambda.amazonaws.com'),
        ManagedPolicyArns: [POLICY.basic],
      },
    };
    const arns = (this.resources[shared].Properties as Props)[
      'ManagedPolicyArns'
    ] as string[];
    policies.forEach((p) => {
      if (!arns.includes(p)) arns.push(p);
    });
    props['Role'] = getAtt(shared, 'Arn');
  }

  private policy(lambdaId: string, arn: string): void {
    const set = this.lambdaPolicies.get(lambdaId) ?? new Set<string>();
    set.add(arn);
    this.lambdaPolicies.set(lambdaId, set);
  }

  private ancestor(
    node: CanvasNode,
    type: AwsServiceType,
  ): CanvasNode | undefined {
    let current = node.parentId ? this.byId.get(node.parentId) : undefined;
    while (current && current.type !== type) {
      current = current.parentId ? this.byId.get(current.parentId) : undefined;
    }
    return current;
  }

  private subnetsIn(vpc: CanvasNode | undefined): CanvasNode[] {
    if (!vpc) return [];
    return this.nodes.filter(
      (n) => n.type === 'subnet' && this.ancestor(n, 'vpc') === vpc,
    );
  }

  private vpcConfig(nodeId: string, key: string, value: unknown): void {
    const props = this.props(nodeId);
    const config = (props['VpcConfig'] ??= {}) as Props;
    push(config, key, value);
  }

  private notification(nodeId: string): Props {
    const props = this.props(nodeId);
    return (props['NotificationConfiguration'] ??= {}) as Props;
  }

  private dependsOn(nodeId: string, logicalId: string): void {
    const resource = this.resources[this.id(nodeId)];
    resource.DependsOn = [
      ...new Set([...(resource.DependsOn ?? []), logicalId]),
    ];
  }
}

function toPascal(text: string): string {
  return text
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((w) => w[0].toUpperCase() + w.slice(1))
    .join('');
}

function coerce(value: string): string | number {
  return /^\d+$/.test(value) ? Number(value) : value;
}

function ref(logicalId: string): Props {
  return { Ref: logicalId };
}

function getAtt(logicalId: string, attribute: string): Props {
  return { 'Fn::GetAtt': [logicalId, attribute] };
}

function push(props: Props, key: string, value: unknown): void {
  const list = (props[key] ??= []) as unknown[];
  list.push(value);
}

function assumeRole(...services: string[]): Props {
  return {
    Version: '2012-10-17',
    Statement: [
      {
        Effect: 'Allow',
        Principal: { Service: services },
        Action: 'sts:AssumeRole',
      },
    ],
  };
}
