import { AwsServiceType, CanvasEdge, CanvasNode } from '@infra-builder/state';

type Props = Record<string, unknown>;

export interface CfResource {
  Type: string;
  Properties?: Props;
  DependsOn?: string[];
}

export interface CfTemplate {
  AWSTemplateFormatVersion: string;
  Description: string;
  Parameters?: Record<string, Props>;
  Resources: Record<string, CfResource>;
}

const RESOURCE_TYPES: Record<AwsServiceType, string> = {
  vpc: 'AWS::EC2::VPC',
  subnet: 'AWS::EC2::Subnet',
  'internet-gateway': 'AWS::EC2::InternetGateway',
  'nat-gateway': 'AWS::EC2::NatGateway',
  ec2: 'AWS::EC2::Instance',
  lambda: 'AWS::Lambda::Function',
  ecs: 'AWS::ECS::Cluster',
  s3: 'AWS::S3::Bucket',
  ebs: 'AWS::EC2::Volume',
  rds: 'AWS::RDS::DBInstance',
  dynamodb: 'AWS::DynamoDB::Table',
  'iam-role': 'AWS::IAM::Role',
  'security-group': 'AWS::EC2::SecurityGroup',
  alb: 'AWS::ElasticLoadBalancingV2::LoadBalancer',
  sqs: 'AWS::SQS::Queue',
  sns: 'AWS::SNS::Topic',
  eventbridge: 'AWS::Events::EventBus',
  'api-gateway': 'AWS::ApiGatewayV2::Api',
  kinesis: 'AWS::Kinesis::Stream',
};

const LATEST_AL2023 =
  '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64}}';

const DEFAULT_PROPS: Partial<Record<AwsServiceType, Props>> = {
  vpc: {
    CidrBlock: '10.0.0.0/16',
    EnableDnsSupport: true,
    EnableDnsHostnames: true,
  },
  subnet: { CidrBlock: '10.0.1.0/24' },
  ec2: { InstanceType: 't3.micro', ImageId: LATEST_AL2023 },
  lambda: {
    Runtime: 'nodejs22.x',
    Handler: 'index.handler',
    Code: {
      ZipFile: 'exports.handler = async () => ({ statusCode: 200 });',
    },
  },
  s3: {
    BucketEncryption: {
      ServerSideEncryptionConfiguration: [
        { ServerSideEncryptionByDefault: { SSEAlgorithm: 'AES256' } },
      ],
    },
  },
  ebs: {
    Size: 8,
    AvailabilityZone: { 'Fn::Select': [0, { 'Fn::GetAZs': '' }] },
  },
  rds: {
    DBInstanceClass: 'db.t3.micro',
    Engine: 'mysql',
    AllocatedStorage: 20,
    MasterUsername: { Ref: 'DBUsername' },
    MasterUserPassword: { Ref: 'DBPassword' },
  },
  dynamodb: {
    KeySchema: [{ AttributeName: 'id', KeyType: 'HASH' }],
    AttributeDefinitions: [{ AttributeName: 'id', AttributeType: 'S' }],
    BillingMode: 'PAY_PER_REQUEST',
  },
  'iam-role': {
    AssumeRolePolicyDocument: assumeRole(
      'lambda.amazonaws.com',
      'ec2.amazonaws.com',
    ),
  },
  'security-group': { GroupDescription: 'Security group' },
  alb: { Type: 'application', Scheme: 'internet-facing' },
  'api-gateway': { ProtocolType: 'HTTP' },
  kinesis: { ShardCount: 1 },
};

const NAT_EIP_PROPS: Props = { Domain: 'vpc' };

/** Per-service AWS principal that may invoke a Lambda. */
const INVOKE_PRINCIPALS: Partial<Record<AwsServiceType, string>> = {
  s3: 's3.amazonaws.com',
  sns: 'sns.amazonaws.com',
  eventbridge: 'events.amazonaws.com',
  'api-gateway': 'apigateway.amazonaws.com',
};

const STREAM_SOURCES: Partial<Record<AwsServiceType, Props>> = {
  sqs: { BatchSize: 10 },
  kinesis: { BatchSize: 100, StartingPosition: 'LATEST' },
  dynamodb: { BatchSize: 100, StartingPosition: 'LATEST' },
};

export function buildTemplate(
  nodes: CanvasNode[],
  edges: CanvasEdge[],
): CfTemplate {
  const ctx = new Builder(nodes);
  nodes.forEach((n) => ctx.addResource(n));
  nodes.forEach((n) => ctx.applyContainment(n));
  edges.forEach((e) => ctx.applyEdge(e));
  ctx.finish();

  const template: CfTemplate = {
    AWSTemplateFormatVersion: '2010-09-09',
    Description: 'Generated by InfraBuilder',
    Resources: ctx.resources,
  };
  if (Object.keys(ctx.parameters).length) template.Parameters = ctx.parameters;
  return template;
}

class Builder {
  readonly resources: Record<string, CfResource> = {};
  readonly parameters: Record<string, Props> = {};
  private readonly ids = new Map<string, string>();
  private readonly byId: Map<string, CanvasNode>;

  constructor(private nodes: CanvasNode[]) {
    this.byId = new Map(nodes.map((n) => [n.id, n]));
    const used = new Set<string>();
    nodes.forEach((n) => {
      const base = toPascal(n.label) || toPascal(n.type) || 'Resource';
      let id = base;
      for (let i = 2; used.has(id); i++) id = `${base}${i}`;
      used.add(id);
      this.ids.set(n.id, id);
    });
  }

  id(nodeId: string): string {
    return this.ids.get(nodeId) as string;
  }

  props(nodeId: string): Props {
    const resource = this.resources[this.id(nodeId)];
    return (resource.Properties ??= {});
  }

  addResource(node: CanvasNode): void {
    const userProps = Object.fromEntries(
      Object.entries(node.properties).map(([k, v]) => [k, coerce(v)]),
    );
    this.resources[this.id(node.id)] = {
      Type: RESOURCE_TYPES[node.type],
      Properties: { ...DEFAULT_PROPS[node.type], ...userProps },
    };
    if (node.type === 'rds') {
      this.parameters['DBUsername'] = { Type: 'String', Default: 'admin' };
      this.parameters['DBPassword'] = { Type: 'String', NoEcho: true };
    }
  }

  applyContainment(node: CanvasNode): void {
    const vpc = this.ancestor(node, 'vpc');
    const subnet = this.ancestor(node, 'subnet');
    const props = this.props(node.id);

    switch (node.type) {
      case 'subnet':
      case 'security-group':
        if (vpc) props['VpcId'] = ref(this.id(vpc.id));
        break;
      case 'ec2':
        if (subnet) props['SubnetId'] = ref(this.id(subnet.id));
        break;
      case 'nat-gateway':
        if (subnet) {
          const eip = `${this.id(node.id)}Eip`;
          this.resources[eip] = {
            Type: 'AWS::EC2::EIP',
            Properties: NAT_EIP_PROPS,
          };
          props['SubnetId'] = ref(this.id(subnet.id));
          props['AllocationId'] = getAtt(eip, 'AllocationId');
        }
        break;
      case 'lambda':
        if (subnet)
          this.vpcConfig(node.id, 'SubnetIds', ref(this.id(subnet.id)));
        break;
      case 'alb':
        if (subnet) push(props, 'Subnets', ref(this.id(subnet.id)));
        break;
      case 'rds':
        if (subnet) {
          const group = `${this.id(node.id)}SubnetGroup`;
          this.resources[group] = {
            Type: 'AWS::RDS::DBSubnetGroup',
            Properties: {
              DBSubnetGroupDescription: `Subnets for ${node.label}`,
              SubnetIds: [ref(this.id(subnet.id))],
            },
          };
          props['DBSubnetGroupName'] = ref(group);
        }
        break;
    }
  }

  applyEdge(edge: CanvasEdge): void {
    const source = this.byId.get(edge.sourceNodeId);
    const target = this.byId.get(edge.targetNodeId);
    if (!source || !target) return;
    const edgeProps = Object.fromEntries(
      Object.entries(edge.properties ?? {}).map(([k, v]) => [k, coerce(v)]),
    );

    switch (edge.kind) {
      case 'trigger':
        this.applyTrigger(source, target, edgeProps);
        break;
      case 'attaches':
        this.applyAttachment(source, target);
        break;
      case 'network':
        this.applyNetwork(source, target);
        break;
      default:
        this.dependsOn(target.id, source.id);
    }
  }

  private applyTrigger(source: CanvasNode, target: CanvasNode, p: Props): void {
    const sourceId = this.id(source.id);
    const targetId = this.id(target.id);
    const fnArn = getAtt(targetId, 'Arn');

    if (target.type === 'lambda' && INVOKE_PRINCIPALS[source.type]) {
      this.resources[`${targetId}${sourceId}Permission`] = {
        Type: 'AWS::Lambda::Permission',
        Properties: {
          Action: 'lambda:InvokeFunction',
          FunctionName: ref(targetId),
          Principal: INVOKE_PRINCIPALS[source.type],
          SourceAccount: ref('AWS::AccountId'),
        },
      };
    }

    if (target.type === 'lambda' && STREAM_SOURCES[source.type]) {
      const arnAttr = source.type === 'dynamodb' ? 'StreamArn' : 'Arn';
      if (source.type === 'dynamodb') {
        this.props(source.id)['StreamSpecification'] = {
          StreamViewType: 'NEW_AND_OLD_IMAGES',
        };
      }
      this.resources[`${targetId}${sourceId}Mapping`] = {
        Type: 'AWS::Lambda::EventSourceMapping',
        Properties: {
          ...STREAM_SOURCES[source.type],
          ...p,
          EventSourceArn: getAtt(sourceId, arnAttr),
          FunctionName: ref(targetId),
        },
      };
      return;
    }

    switch (source.type) {
      case 's3': {
        const config: Props = {
          Event: p['Event'] ?? 's3:ObjectCreated:*',
          Function: fnArn,
        };
        if (p['Prefix']) {
          config['Filter'] = {
            S3Key: { Rules: [{ Name: 'prefix', Value: p['Prefix'] }] },
          };
        }
        push(this.notification(source.id), 'LambdaConfigurations', config);
        this.dependsOn(source.id, `${targetId}${sourceId}Permission`, true);
        break;
      }
      case 'sns':
        this.resources[`${sourceId}${targetId}Subscription`] = {
          Type: 'AWS::SNS::Subscription',
          Properties: {
            TopicArn: ref(sourceId),
            Protocol: target.type === 'sqs' ? 'sqs' : 'lambda',
            Endpoint: getAtt(targetId, 'Arn'),
          },
        };
        break;
      case 'eventbridge': {
        const rule: Props = {
          EventBusName: ref(sourceId),
          Targets: [{ Arn: getAtt(targetId, 'Arn'), Id: targetId }],
        };
        if (p['ScheduleExpression']) {
          rule['ScheduleExpression'] = p['ScheduleExpression'];
          delete rule['EventBusName'];
        } else {
          rule['EventPattern'] = {
            source: [{ 'Fn::Sub': '${AWS::StackName}' }],
          };
        }
        this.resources[`${sourceId}${targetId}Rule`] = {
          Type: 'AWS::Events::Rule',
          Properties: rule,
        };
        break;
      }
      case 'api-gateway': {
        const integration = `${sourceId}${targetId}Integration`;
        this.resources[integration] = {
          Type: 'AWS::ApiGatewayV2::Integration',
          Properties: {
            ApiId: ref(sourceId),
            IntegrationType: 'AWS_PROXY',
            IntegrationUri: fnArn,
            PayloadFormatVersion: '2.0',
          },
        };
        this.resources[`${sourceId}${targetId}Route`] = {
          Type: 'AWS::ApiGatewayV2::Route',
          Properties: {
            ApiId: ref(sourceId),
            RouteKey: p['RouteKey'] ?? '$default',
            Target: { 'Fn::Sub': `integrations/\${${integration}}` },
          },
        };
        break;
      }
    }
  }

  private applyAttachment(source: CanvasNode, target: CanvasNode): void {
    const sourceId = this.id(source.id);
    const targetId = this.id(target.id);
    const targetProps = this.props(target.id);

    if (source.type === 'iam-role') {
      if (target.type === 'lambda') {
        targetProps['Role'] = getAtt(sourceId, 'Arn');
      } else if (target.type === 'ec2') {
        const profile = `${sourceId}InstanceProfile`;
        this.resources[profile] ??= {
          Type: 'AWS::IAM::InstanceProfile',
          Properties: { Roles: [ref(sourceId)] },
        };
        targetProps['IamInstanceProfile'] = ref(profile);
      }
    } else if (source.type === 'security-group') {
      const key: Partial<Record<AwsServiceType, string>> = {
        ec2: 'SecurityGroupIds',
        rds: 'VPCSecurityGroups',
        alb: 'SecurityGroups',
      };
      if (target.type === 'lambda') {
        this.vpcConfig(target.id, 'SecurityGroupIds', ref(sourceId));
      } else if (key[target.type]) {
        push(targetProps, key[target.type] as string, ref(sourceId));
      }
    } else if (source.type === 'ebs' && target.type === 'ec2') {
      this.resources[`${targetId}${sourceId}Attachment`] = {
        Type: 'AWS::EC2::VolumeAttachment',
        Properties: {
          InstanceId: ref(targetId),
          VolumeId: ref(sourceId),
          Device: '/dev/sdf',
        },
      };
    }
  }

  private applyNetwork(source: CanvasNode, target: CanvasNode): void {
    const sourceId = this.id(source.id);
    const targetId = this.id(target.id);

    if (source.type === 'internet-gateway' && target.type === 'vpc') {
      this.resources[`${targetId}${sourceId}Attachment`] = {
        Type: 'AWS::EC2::VPCGatewayAttachment',
        Properties: { VpcId: ref(targetId), InternetGatewayId: ref(sourceId) },
      };
    } else if (source.type === 'alb' && target.type === 'ec2') {
      const vpc = this.ancestor(source, 'vpc');
      const group = `${sourceId}TargetGroup`;
      this.resources[group] ??= {
        Type: 'AWS::ElasticLoadBalancingV2::TargetGroup',
        Properties: {
          Port: 80,
          Protocol: 'HTTP',
          TargetType: 'instance',
          ...(vpc ? { VpcId: ref(this.id(vpc.id)) } : {}),
          Targets: [],
        },
      };
      push(this.resources[group].Properties as Props, 'Targets', {
        Id: ref(targetId),
      });
      this.resources[`${sourceId}Listener`] ??= {
        Type: 'AWS::ElasticLoadBalancingV2::Listener',
        Properties: {
          LoadBalancerArn: ref(sourceId),
          Port: 80,
          Protocol: 'HTTP',
          DefaultActions: [{ Type: 'forward', TargetGroupArn: ref(group) }],
        },
      };
    } else {
      this.dependsOn(target.id, source.id);
    }
  }

  finish(): void {
    const roleless = this.nodes.filter(
      (n) => n.type === 'lambda' && !this.props(n.id)['Role'],
    );
    if (roleless.length === 0) return;
    this.resources['LambdaExecutionRole'] = {
      Type: 'AWS::IAM::Role',
      Properties: {
        AssumeRolePolicyDocument: assumeRole('lambda.amazonaws.com'),
        ManagedPolicyArns: [
          'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole',
        ],
      },
    };
    roleless.forEach((n) => {
      this.props(n.id)['Role'] = getAtt('LambdaExecutionRole', 'Arn');
    });
  }

  private ancestor(
    node: CanvasNode,
    type: AwsServiceType,
  ): CanvasNode | undefined {
    let current = node.parentId ? this.byId.get(node.parentId) : undefined;
    while (current && current.type !== type) {
      current = current.parentId ? this.byId.get(current.parentId) : undefined;
    }
    return current;
  }

  private vpcConfig(nodeId: string, key: string, value: unknown): void {
    const props = this.props(nodeId);
    const config = (props['VpcConfig'] ??= {}) as Props;
    push(config, key, value);
  }

  private notification(nodeId: string): Props {
    const props = this.props(nodeId);
    return (props['NotificationConfiguration'] ??= {}) as Props;
  }

  /** Adds a DependsOn entry; `raw` when the dependency is a logical id already. */
  private dependsOn(nodeId: string, dependency: string, raw = false): void {
    const resource = this.resources[this.id(nodeId)];
    const dep = raw ? dependency : this.id(dependency);
    resource.DependsOn = [...new Set([...(resource.DependsOn ?? []), dep])];
  }
}

function toPascal(text: string): string {
  return text
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((w) => w[0].toUpperCase() + w.slice(1))
    .join('');
}

function coerce(value: string): string | number {
  return /^\d+$/.test(value) ? Number(value) : value;
}

function ref(logicalId: string): Props {
  return { Ref: logicalId };
}

function getAtt(logicalId: string, attribute: string): Props {
  return { 'Fn::GetAtt': [logicalId, attribute] };
}

function push(props: Props, key: string, value: unknown): void {
  const list = (props[key] ??= []) as unknown[];
  list.push(value);
}

function assumeRole(...services: string[]): Props {
  return {
    Version: '2012-10-17',
    Statement: [
      {
        Effect: 'Allow',
        Principal: { Service: services },
        Action: 'sts:AssumeRole',
      },
    ],
  };
}
